// User reducer types
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";
export const SET_USER = "SET_USER";
export const LOADING_USER = "LOADING_USER";
export const SET_USER_HAS_TRANSACTIONS = "SET_USER_HAS_TRANSACTIONS";
// UI reducer types
export const SET_ERRORS = "SET_ERRORS";
export const LOADING_UI = "LOADING_UI";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_ERRORS_BUT_NOT_ALERT = "CLEAR_ERRORS_BUT_NOT_ALERT";
export const SHOW_ALERT = "SHOW_ALERT";
// Data reducer types
export const SET_TRANSACTIONS = "SET_TRANSACTIONS";
export const SET_HASTRANSACTIONS = "SET_HASTRANSACTIONS";
export const SET_COINS = "SET_COINS";
export const SET_PORTFOLIO = "SET_PORTFOLIO";
export const REMOVE_TRANSACTION_FROM_STATE = "REMOVE_TRANSACTION_FROM_STATE";
export const SET_STATICPORTFOLIO = "SET_STATICPORTFOLIO";
export const SET_TIMESERIESPORTFOLIO = "SET_TIMESERIESPORTFOLIO";
